package faena;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 309Control
 */
public class Ingreso extends javax.swing.JFrame {

    /**
     * Creates new form Ingreso
     */
    public Ingreso() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextId = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jTextPrecio = new javax.swing.JTextField();
        jTextCantidad = new javax.swing.JTextField();
        jTextStock = new javax.swing.JTextField();
        jTextProveedor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextComentario = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("INGRESO PRODUCTOS:");

        jTextId.setText("ID");
        jTextId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextIdFocusLost(evt);
            }
        });
        jTextId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextIdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextIdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextIdMouseExited(evt);
            }
        });
        jTextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdActionPerformed(evt);
            }
        });

        jTextNombre.setText("NOMBRE");
        jTextNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextNombreFocusGained(evt);
            }
        });
        jTextNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextNombreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextNombreMouseExited(evt);
            }
        });
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });

        jTextPrecio.setText("PRECIO");
        jTextPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextPrecioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextPrecioMouseExited(evt);
            }
        });

        jTextCantidad.setText("CANTIDAD");
        jTextCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextCantidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextCantidadMouseExited(evt);
            }
        });

        jTextStock.setText("STOCK");
        jTextStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextStockMouseExited(evt);
            }
        });

        jTextProveedor.setText("PROVEEDOR");
        jTextProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextProveedorMouseExited(evt);
            }
        });

        jTextComentario.setColumns(20);
        jTextComentario.setRows(5);
        jTextComentario.setText("COMENTARIO");
        jTextComentario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextComentarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextComentarioMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(jTextComentario);

        jButton1.setText("REGISTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextPrecio)
                            .addComponent(jTextNombre)
                            .addComponent(jTextId)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextCantidad)
                            .addComponent(jTextStock)
                            .addComponent(jTextProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jTextId))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextStock, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(jTextNombre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jTextPrecio)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTextIdActionPerformed

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ControllerFaena nueva_venta = new ControllerFaena();
        boolean resultado;
        resultado = nueva_venta.Insertar_Producto(jTextId.getText(), jTextNombre.getText(), jTextPrecio.getText(), jTextCantidad.getText(), jTextStock.getText(), jTextProveedor.getText(), jTextComentario.getText());
        if(resultado){
            JOptionPane.showMessageDialog(null, "Registrado el Producto Correctamente");
        }else{
            JOptionPane.showMessageDialog(null, "Error, complete los campos correctamente");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void jTextIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextIdMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextIdMouseClicked

    private void jTextIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextIdFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTextIdFocusLost

    private void jTextIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextIdFocusGained
        // TODO add your handling code here:
        //jTextId.setText("");
      
    }//GEN-LAST:event_jTextIdFocusGained

    private void jTextNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNombreFocusGained
        // TODO add your handling code here:
      
      
    }//GEN-LAST:event_jTextNombreFocusGained

    private void jTextIdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextIdMouseEntered
        // TODO add your handling code here:
        if(jTextId.getText().equals("ID")){
            jTextId.setText("");
        }
    }//GEN-LAST:event_jTextIdMouseEntered

    private void jTextIdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextIdMouseExited
        // TODO add your handling code here:
        if(jTextId.getText().equals("")){
            jTextId.setText("ID");
        }
    }//GEN-LAST:event_jTextIdMouseExited

    private void jTextNombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextNombreMouseEntered
        // TODO add your handling code here:
        if(jTextNombre.getText().equals("NOMBRE")){
            jTextNombre.setText("");
        }
    }//GEN-LAST:event_jTextNombreMouseEntered

    private void jTextNombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextNombreMouseExited
        // TODO add your handling code here:
        if(jTextNombre.getText().equals("")){
            jTextNombre.setText("NOMBRE");
        }
    }//GEN-LAST:event_jTextNombreMouseExited

    private void jTextPrecioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPrecioMouseEntered
        // TODO add your handling code here:
        if(jTextPrecio.getText().equals("PRECIO")){
            jTextPrecio.setText("");
        }
    }//GEN-LAST:event_jTextPrecioMouseEntered

    private void jTextCantidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextCantidadMouseEntered
        // TODO add your handling code here:
        if(jTextCantidad.getText().equals("CANTIDAD")){
            jTextCantidad.setText("");
        }
    }//GEN-LAST:event_jTextCantidadMouseEntered

    private void jTextStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextStockMouseEntered
        // TODO add your handling code here:
        if(jTextStock.getText().equals("STOCK")){
            jTextStock.setText("");
        }
    }//GEN-LAST:event_jTextStockMouseEntered

    private void jTextProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextProveedorMouseEntered
        // TODO add your handling code here:
        if(jTextProveedor.getText().equals("PROVEEDOR")){
            jTextProveedor.setText("");
        }
    }//GEN-LAST:event_jTextProveedorMouseEntered

    private void jTextComentarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextComentarioMouseEntered
        // TODO add your handling code here:
        if(jTextComentario.getText().equals("COMENTARIO")){
            jTextComentario.setText("");
        }
    }//GEN-LAST:event_jTextComentarioMouseEntered

    private void jTextPrecioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPrecioMouseExited
        // TODO add your handling code here:
        if(jTextPrecio.getText().equals("")){
            jTextPrecio.setText("PRECIO");
        }
    }//GEN-LAST:event_jTextPrecioMouseExited

    private void jTextCantidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextCantidadMouseExited
        // TODO add your handling code here:
        if(jTextCantidad.getText().equals("")){
            jTextCantidad.setText("CANTIDAD");
        }
    }//GEN-LAST:event_jTextCantidadMouseExited

    private void jTextStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextStockMouseExited
        // TODO add your handling code here:
        if(jTextStock.getText().equals("")){
            jTextStock.setText("STOCK");
        }
    }//GEN-LAST:event_jTextStockMouseExited

    private void jTextProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextProveedorMouseExited
        // TODO add your handling code here:
        if(jTextProveedor.getText().equals("")){
            jTextProveedor.setText("PROVEEDOR");
        }
    }//GEN-LAST:event_jTextProveedorMouseExited

    private void jTextComentarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextComentarioMouseExited
        // TODO add your handling code here:
        if(jTextComentario.getText().equals("")){
            jTextComentario.setText("COMENTARIO");
        }
    }//GEN-LAST:event_jTextComentarioMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextCantidad;
    private javax.swing.JTextArea jTextComentario;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextPrecio;
    private javax.swing.JTextField jTextProveedor;
    private javax.swing.JTextField jTextStock;
    // End of variables declaration//GEN-END:variables
}
